name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (sanity check)
        run: |
          pwd
          ls -la

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make

      - name: Build & run tests
        run: |
          make clean || true
          make test 2>&1 | tee build.log

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
